FROM python:3.8-slim-buster
WORKDIR /server

COPY . .
RUN pip install openslide-python openslide-bin
RUN pip3 install -r requirements.txt

CMD ["gunicorn", "--bind", "0.0.0.0:5000", "wsgi:app", "--workers=4"]